[package]
name = "wevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.1" }
bevy_common_assets = { version = "0.8.0", features = ["json"] }
serde = "1.0.194"
